### ISSUE TITLE
Question for shadow jar

### ISSUE THREAD

**Issue by giwa** [embulk/gradle-embulk-plugins#82]
I tried to use this plugin for bq_java output plugin. But I could not figure out a workaround of shadow jar for the incompatibility with Guava's version from Embulk.

https://github.com/trocco-io/embulk-output-bigquery_java/pull/16

like 
https://github.com/embulk/embulk-input-gcs/blob/master/build.gradle#L50-L57

Is there any workaround for this?

**Comment by dmikurube** [comment]
We're going to prepare some possible workarounds, but no very good workaround yet. Stay tuned!
